// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEjU7WOfpoYmmqCEvlQGkO2bGDd4I6qE',
    appId: '1:86545149644:web:80664c70710ab6d8c95c69',
    messagingSenderId: '86545149644',
    projectId: 'women-safety-sos-75b32',
    authDomain: 'women-safety-sos-75b32.firebaseapp.com',
    storageBucket: 'women-safety-sos-75b32.appspot.com',
    measurementId: 'G-F51QWJBK1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZesdcw2YLJPegIbp3EOc8ToC1OVo2U8',
    appId: '1:86545149644:android:64e7445605add5f5c95c69',
    messagingSenderId: '86545149644',
    projectId: 'women-safety-sos-75b32',
    storageBucket: 'women-safety-sos-75b32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS0mpycDjV-7zY2TDMstJUblQqwXVI_LE',
    appId: '1:86545149644:ios:e2a83fd9e1110546c95c69',
    messagingSenderId: '86545149644',
    projectId: 'women-safety-sos-75b32',
    storageBucket: 'women-safety-sos-75b32.appspot.com',
    iosBundleId: 'com.example.womenSafty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS0mpycDjV-7zY2TDMstJUblQqwXVI_LE',
    appId: '1:86545149644:ios:e2a83fd9e1110546c95c69',
    messagingSenderId: '86545149644',
    projectId: 'women-safety-sos-75b32',
    storageBucket: 'women-safety-sos-75b32.appspot.com',
    iosBundleId: 'com.example.womenSafty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLEjU7WOfpoYmmqCEvlQGkO2bGDd4I6qE',
    appId: '1:86545149644:web:22726572f523998fc95c69',
    messagingSenderId: '86545149644',
    projectId: 'women-safety-sos-75b32',
    authDomain: 'women-safety-sos-75b32.firebaseapp.com',
    storageBucket: 'women-safety-sos-75b32.appspot.com',
    measurementId: 'G-PV49MHDNKG',
  );
}
